version: "2"

run:
  timeout: 5m

linters:
  default: none

  exclusions:
    presets:
      - comments

  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - revive
    - errorlint
    - bodyclose
    - copyloopvar

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0