// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: item_queue_member.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countItemQueueMembers = `-- name: CountItemQueueMembers :one
SELECT COUNT(*)
FROM item_queue_members
WHERE item_id = $1
`

func (q *Queries) CountItemQueueMembers(ctx context.Context, itemID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countItemQueueMembers, itemID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createItemQueueMember = `-- name: CreateItemQueueMember :one
INSERT INTO item_queue_members (
    item_id,
    user_id,
    ticket_id,
    position,
    status,
    created_at
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING 
    id,
    item_id,
    user_id,
    ticket_id,
    position,
    status,
    created_at
`

type CreateItemQueueMemberParams struct {
	ItemID    pgtype.UUID      `json:"item_id"`
	UserID    pgtype.UUID      `json:"user_id"`
	TicketID  pgtype.UUID      `json:"ticket_id"`
	Position  int32            `json:"position"`
	Status    string           `json:"status"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateItemQueueMember(ctx context.Context, arg CreateItemQueueMemberParams) (ItemQueueMember, error) {
	row := q.db.QueryRow(ctx, createItemQueueMember,
		arg.ItemID,
		arg.UserID,
		arg.TicketID,
		arg.Position,
		arg.Status,
		arg.CreatedAt,
	)
	var i ItemQueueMember
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.UserID,
		&i.TicketID,
		&i.Position,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllItemQueueMembersByItemID = `-- name: DeleteAllItemQueueMembersByItemID :exec
DELETE FROM item_queue_members
WHERE item_id = $1
`

func (q *Queries) DeleteAllItemQueueMembersByItemID(ctx context.Context, itemID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllItemQueueMembersByItemID, itemID)
	return err
}

const deleteItemQueueMember = `-- name: DeleteItemQueueMember :exec
DELETE FROM item_queue_members
WHERE item_id = $1 
AND user_id = $2
`

type DeleteItemQueueMemberParams struct {
	ItemID pgtype.UUID `json:"item_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteItemQueueMember(ctx context.Context, arg DeleteItemQueueMemberParams) error {
	_, err := q.db.Exec(ctx, deleteItemQueueMember, arg.ItemID, arg.UserID)
	return err
}

const existsItemQueueMember = `-- name: ExistsItemQueueMember :one
SELECT EXISTS(
    SELECT 1
    FROM item_queue_members
    WHERE item_id = $1 
    AND user_id = $2
)
`

type ExistsItemQueueMemberParams struct {
	ItemID pgtype.UUID `json:"item_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) ExistsItemQueueMember(ctx context.Context, arg ExistsItemQueueMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsItemQueueMember, arg.ItemID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getAllItemQueueMembersByItemID = `-- name: GetAllItemQueueMembersByItemID :many
SELECT 
    id,
    item_id,
    user_id,
    ticket_id,
    position,
    status,
    created_at
FROM item_queue_members
WHERE item_id = $1
ORDER BY position
`

func (q *Queries) GetAllItemQueueMembersByItemID(ctx context.Context, itemID pgtype.UUID) ([]ItemQueueMember, error) {
	rows, err := q.db.Query(ctx, getAllItemQueueMembersByItemID, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemQueueMember{}
	for rows.Next() {
		var i ItemQueueMember
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.UserID,
			&i.TicketID,
			&i.Position,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllItemQueueMembersByUserID = `-- name: GetAllItemQueueMembersByUserID :many
SELECT 
    id,
    item_id,
    user_id,
    ticket_id,
    position,
    status,
    created_at
FROM item_queue_members
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) GetAllItemQueueMembersByUserID(ctx context.Context, userID pgtype.UUID) ([]ItemQueueMember, error) {
	rows, err := q.db.Query(ctx, getAllItemQueueMembersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemQueueMember{}
	for rows.Next() {
		var i ItemQueueMember
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.UserID,
			&i.TicketID,
			&i.Position,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemQueueMemberByUserID = `-- name: GetItemQueueMemberByUserID :one
SELECT 
    id,
    item_id,
    user_id,
    ticket_id,
    position,
    status,
    created_at
FROM item_queue_members
WHERE item_id = $1 
AND user_id = $2
`

type GetItemQueueMemberByUserIDParams struct {
	ItemID pgtype.UUID `json:"item_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetItemQueueMemberByUserID(ctx context.Context, arg GetItemQueueMemberByUserIDParams) (ItemQueueMember, error) {
	row := q.db.QueryRow(ctx, getItemQueueMemberByUserID, arg.ItemID, arg.UserID)
	var i ItemQueueMember
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.UserID,
		&i.TicketID,
		&i.Position,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getItemQueueMemberPosition = `-- name: GetItemQueueMemberPosition :one
SELECT position
FROM item_queue_members
WHERE item_id = $1
AND user_id = $2
`

type GetItemQueueMemberPositionParams struct {
	ItemID pgtype.UUID `json:"item_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetItemQueueMemberPosition(ctx context.Context, arg GetItemQueueMemberPositionParams) (int32, error) {
	row := q.db.QueryRow(ctx, getItemQueueMemberPosition, arg.ItemID, arg.UserID)
	var position int32
	err := row.Scan(&position)
	return position, err
}

const shiftItemQueueMembersPositions = `-- name: ShiftItemQueueMembersPositions :exec
UPDATE item_queue_members
SET position = position - 1
WHERE item_id = $1
AND position > $2
`

type ShiftItemQueueMembersPositionsParams struct {
	ItemID   pgtype.UUID `json:"item_id"`
	Position int32       `json:"position"`
}

func (q *Queries) ShiftItemQueueMembersPositions(ctx context.Context, arg ShiftItemQueueMembersPositionsParams) error {
	_, err := q.db.Exec(ctx, shiftItemQueueMembersPositions, arg.ItemID, arg.Position)
	return err
}

const updateItemQueueMember = `-- name: UpdateItemQueueMember :exec
UPDATE item_queue_members
SET 
    ticket_id = $3,
    position = $4,
    status = $5
WHERE item_id = $1 
AND user_id = $2
`

type UpdateItemQueueMemberParams struct {
	ItemID   pgtype.UUID `json:"item_id"`
	UserID   pgtype.UUID `json:"user_id"`
	TicketID pgtype.UUID `json:"ticket_id"`
	Position int32       `json:"position"`
	Status   string      `json:"status"`
}

func (q *Queries) UpdateItemQueueMember(ctx context.Context, arg UpdateItemQueueMemberParams) error {
	_, err := q.db.Exec(ctx, updateItemQueueMember,
		arg.ItemID,
		arg.UserID,
		arg.TicketID,
		arg.Position,
		arg.Status,
	)
	return err
}
