// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: item_queue.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createItemQueue = `-- name: CreateItemQueue :exec
INSERT INTO item_queues (
    item_id,
    state,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4)
`

type CreateItemQueueParams struct {
	ItemID    pgtype.UUID      `json:"item_id"`
	State     string           `json:"state"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateItemQueue(ctx context.Context, arg CreateItemQueueParams) error {
	_, err := q.db.Exec(ctx, createItemQueue,
		arg.ItemID,
		arg.State,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteItemQueue = `-- name: DeleteItemQueue :exec
DELETE FROM item_queues
WHERE item_id = $1
`

func (q *Queries) DeleteItemQueue(ctx context.Context, itemID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteItemQueue, itemID)
	return err
}

const existsItemQueue = `-- name: ExistsItemQueue :one
SELECT EXISTS(
    SELECT 1
    FROM item_queues
    WHERE item_id = $1
)
`

func (q *Queries) ExistsItemQueue(ctx context.Context, itemID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, existsItemQueue, itemID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getItemQueueByID = `-- name: GetItemQueueByID :one
SELECT
    item_id,
    state,
    created_at,
    updated_at
FROM item_queues
WHERE item_id = $1
`

func (q *Queries) GetItemQueueByID(ctx context.Context, itemID pgtype.UUID) (ItemQueue, error) {
	row := q.db.QueryRow(ctx, getItemQueueByID, itemID)
	var i ItemQueue
	err := row.Scan(
		&i.ItemID,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockItemQueue = `-- name: LockItemQueue :one
SELECT
    item_id,
    state,
    created_at,
    updated_at
FROM item_queues
WHERE item_id = $1
FOR UPDATE
`

func (q *Queries) LockItemQueue(ctx context.Context, itemID pgtype.UUID) (ItemQueue, error) {
	row := q.db.QueryRow(ctx, lockItemQueue, itemID)
	var i ItemQueue
	err := row.Scan(
		&i.ItemID,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateItemQueue = `-- name: UpdateItemQueue :exec
UPDATE item_queues
SET
    state = $2,
    updated_at = $3
WHERE item_id = $1
`

type UpdateItemQueueParams struct {
	ItemID    pgtype.UUID      `json:"item_id"`
	State     string           `json:"state"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpdateItemQueue(ctx context.Context, arg UpdateItemQueueParams) error {
	_, err := q.db.Exec(ctx, updateItemQueue, arg.ItemID, arg.State, arg.UpdatedAt)
	return err
}
