// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: item_queue_member.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createItemQueueMember = `-- name: CreateItemQueueMember :one
INSERT INTO item_queue_members (
    item_id,
    user_id,
    ticket_id,
    position,
    status,
    created_at
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
    id,
    item_id,
    user_id,
    ticket_id,
    position,
    status,
    created_at
`

type CreateItemQueueMemberParams struct {
	ItemID    pgtype.UUID      `json:"item_id"`
	UserID    pgtype.UUID      `json:"user_id"`
	TicketID  pgtype.UUID      `json:"ticket_id"`
	Position  pgtype.Int4      `json:"position"`
	Status    string           `json:"status"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateItemQueueMember(ctx context.Context, arg CreateItemQueueMemberParams) (ItemQueueMember, error) {
	row := q.db.QueryRow(ctx, createItemQueueMember,
		arg.ItemID,
		arg.UserID,
		arg.TicketID,
		arg.Position,
		arg.Status,
		arg.CreatedAt,
	)
	var i ItemQueueMember
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.UserID,
		&i.TicketID,
		&i.Position,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllItemQueueMembersByItemID = `-- name: DeleteAllItemQueueMembersByItemID :exec
DELETE FROM item_queue_members
WHERE item_id = $1
`

func (q *Queries) DeleteAllItemQueueMembersByItemID(ctx context.Context, itemID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllItemQueueMembersByItemID, itemID)
	return err
}

const existsItemQueueMember = `-- name: ExistsItemQueueMember :one
SELECT EXISTS(
    SELECT 1
    FROM item_queue_members
    WHERE item_id = $1
    AND user_id = $2
)
`

type ExistsItemQueueMemberParams struct {
	ItemID pgtype.UUID `json:"item_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) ExistsItemQueueMember(ctx context.Context, arg ExistsItemQueueMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsItemQueueMember, arg.ItemID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getAllItemQueueMembersByItemID = `-- name: GetAllItemQueueMembersByItemID :many
SELECT
    id,
    item_id,
    user_id,
    ticket_id,
    position,
    status,
    created_at
FROM item_queue_members
WHERE item_id = $1
ORDER BY position NULLS LAST
`

func (q *Queries) GetAllItemQueueMembersByItemID(ctx context.Context, itemID pgtype.UUID) ([]ItemQueueMember, error) {
	rows, err := q.db.Query(ctx, getAllItemQueueMembersByItemID, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemQueueMember{}
	for rows.Next() {
		var i ItemQueueMember
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.UserID,
			&i.TicketID,
			&i.Position,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllItemQueueMembersByUserID = `-- name: GetAllItemQueueMembersByUserID :many
SELECT
    id,
    item_id,
    user_id,
    ticket_id,
    position,
    status,
    created_at
FROM item_queue_members
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) GetAllItemQueueMembersByUserID(ctx context.Context, userID pgtype.UUID) ([]ItemQueueMember, error) {
	rows, err := q.db.Query(ctx, getAllItemQueueMembersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemQueueMember{}
	for rows.Next() {
		var i ItemQueueMember
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.UserID,
			&i.TicketID,
			&i.Position,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemQueueMemberByTicketID = `-- name: GetItemQueueMemberByTicketID :one
SELECT
    id,
    item_id,
    user_id,
    ticket_id,
    position,
    status,
    created_at
FROM item_queue_members
WHERE ticket_id = $1
`

func (q *Queries) GetItemQueueMemberByTicketID(ctx context.Context, ticketID pgtype.UUID) (ItemQueueMember, error) {
	row := q.db.QueryRow(ctx, getItemQueueMemberByTicketID, ticketID)
	var i ItemQueueMember
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.UserID,
		&i.TicketID,
		&i.Position,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getItemQueueMemberByUserID = `-- name: GetItemQueueMemberByUserID :one
SELECT
    id,
    item_id,
    user_id,
    ticket_id,
    position,
    status,
    created_at
FROM item_queue_members
WHERE item_id = $1
AND user_id = $2
`

type GetItemQueueMemberByUserIDParams struct {
	ItemID pgtype.UUID `json:"item_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetItemQueueMemberByUserID(ctx context.Context, arg GetItemQueueMemberByUserIDParams) (ItemQueueMember, error) {
	row := q.db.QueryRow(ctx, getItemQueueMemberByUserID, arg.ItemID, arg.UserID)
	var i ItemQueueMember
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.UserID,
		&i.TicketID,
		&i.Position,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getItemQueueMemberPosition = `-- name: GetItemQueueMemberPosition :one
SELECT
    position
FROM item_queue_members
WHERE item_id = $1
AND user_id = $2
`

type GetItemQueueMemberPositionParams struct {
	ItemID pgtype.UUID `json:"item_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetItemQueueMemberPosition(ctx context.Context, arg GetItemQueueMemberPositionParams) (pgtype.Int4, error) {
	row := q.db.QueryRow(ctx, getItemQueueMemberPosition, arg.ItemID, arg.UserID)
	var position pgtype.Int4
	err := row.Scan(&position)
	return position, err
}

const getRealUserQueuePosition = `-- name: GetRealUserQueuePosition :one
SELECT COUNT(*) + 1 AS position
FROM item_queue_members
WHERE item_queue_members.item_id = $1
AND item_queue_members.status IN (
    'waiting_in_line',
    'acquired_purchase_rights',
    'placed_an_order'
)
AND item_queue_members.position < (
    SELECT position
    FROM item_queue_members
    WHERE item_queue_members.item_id = $1
    AND item_queue_members.user_id = $2
)
`

type GetRealUserQueuePositionParams struct {
	ItemID pgtype.UUID `json:"item_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetRealUserQueuePosition(ctx context.Context, arg GetRealUserQueuePositionParams) (int32, error) {
	row := q.db.QueryRow(ctx, getRealUserQueuePosition, arg.ItemID, arg.UserID)
	var position int32
	err := row.Scan(&position)
	return position, err
}

const getUserQueueRank = `-- name: GetUserQueueRank :one
SELECT COUNT(*) + 1 AS rank
FROM item_queue_members outer_q
WHERE outer_q.item_id = $1
AND outer_q.position <= (
    SELECT inner_q.position 
    FROM item_queue_members inner_q 
    WHERE inner_q.item_id = $1 
    AND inner_q.user_id = $2
)
`

type GetUserQueueRankParams struct {
	ItemID pgtype.UUID `json:"item_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetUserQueueRank(ctx context.Context, arg GetUserQueueRankParams) (int32, error) {
	row := q.db.QueryRow(ctx, getUserQueueRank, arg.ItemID, arg.UserID)
	var rank int32
	err := row.Scan(&rank)
	return rank, err
}

const leaveItemQueueMember = `-- name: LeaveItemQueueMember :exec
UPDATE item_queue_members
SET
    status = $3,
    position = NULL
WHERE item_id = $1
AND user_id = $2
`

type LeaveItemQueueMemberParams struct {
	ItemID pgtype.UUID `json:"item_id"`
	UserID pgtype.UUID `json:"user_id"`
	Status string      `json:"status"`
}

func (q *Queries) LeaveItemQueueMember(ctx context.Context, arg LeaveItemQueueMemberParams) error {
	_, err := q.db.Exec(ctx, leaveItemQueueMember, arg.ItemID, arg.UserID, arg.Status)
	return err
}

const reactivateItemQueueMember = `-- name: ReactivateItemQueueMember :exec
UPDATE item_queue_members
SET
    status = 'waiting_in_line',
    position = $3,
    ticket_id = NULL
WHERE item_id = $1
AND user_id = $2
`

type ReactivateItemQueueMemberParams struct {
	ItemID   pgtype.UUID `json:"item_id"`
	UserID   pgtype.UUID `json:"user_id"`
	Position pgtype.Int4 `json:"position"`
}

func (q *Queries) ReactivateItemQueueMember(ctx context.Context, arg ReactivateItemQueueMemberParams) error {
	_, err := q.db.Exec(ctx, reactivateItemQueueMember, arg.ItemID, arg.UserID, arg.Position)
	return err
}

const shiftItemQueueMembersPositions = `-- name: ShiftItemQueueMembersPositions :exec
UPDATE item_queue_members
SET position = position - 1
WHERE item_id = $1
AND position > $2
`

type ShiftItemQueueMembersPositionsParams struct {
	ItemID   pgtype.UUID `json:"item_id"`
	Position pgtype.Int4 `json:"position"`
}

func (q *Queries) ShiftItemQueueMembersPositions(ctx context.Context, arg ShiftItemQueueMembersPositionsParams) error {
	_, err := q.db.Exec(ctx, shiftItemQueueMembersPositions, arg.ItemID, arg.Position)
	return err
}

const updateItemQueueMember = `-- name: UpdateItemQueueMember :exec
UPDATE item_queue_members
SET
    ticket_id = $3,
    position = $4,
    status = $5
WHERE item_id = $1
AND user_id = $2
`

type UpdateItemQueueMemberParams struct {
	ItemID   pgtype.UUID `json:"item_id"`
	UserID   pgtype.UUID `json:"user_id"`
	TicketID pgtype.UUID `json:"ticket_id"`
	Position pgtype.Int4 `json:"position"`
	Status   string      `json:"status"`
}

func (q *Queries) UpdateItemQueueMember(ctx context.Context, arg UpdateItemQueueMemberParams) error {
	_, err := q.db.Exec(ctx, updateItemQueueMember,
		arg.ItemID,
		arg.UserID,
		arg.TicketID,
		arg.Position,
		arg.Status,
	)
	return err
}
