// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ItemQueue struct {
	ItemID    pgtype.UUID      `json:"item_id"`
	State     string           `json:"state"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type ItemQueueMember struct {
	ItemID    pgtype.UUID      `json:"item_id"`
	UserID    pgtype.UUID      `json:"user_id"`
	Position  int32            `json:"position"`
	Status    string           `json:"status"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
