// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountItemQueueMembers(ctx context.Context, itemID pgtype.UUID) (int64, error)
	CreateItemQueue(ctx context.Context, arg CreateItemQueueParams) error
	CreateItemQueueMember(ctx context.Context, arg CreateItemQueueMemberParams) (ItemQueueMember, error)
	DeleteAllItemQueueMembersByItemID(ctx context.Context, itemID pgtype.UUID) error
	DeleteItemQueue(ctx context.Context, itemID pgtype.UUID) error
	DeleteItemQueueMember(ctx context.Context, arg DeleteItemQueueMemberParams) error
	ExistsItemQueue(ctx context.Context, itemID pgtype.UUID) (bool, error)
	ExistsItemQueueMember(ctx context.Context, arg ExistsItemQueueMemberParams) (bool, error)
	GetAllItemQueueMembersByItemID(ctx context.Context, itemID pgtype.UUID) ([]ItemQueueMember, error)
	GetAllItemQueueMembersByUserID(ctx context.Context, userID pgtype.UUID) ([]ItemQueueMember, error)
	GetItemQueueByID(ctx context.Context, itemID pgtype.UUID) (ItemQueue, error)
	GetItemQueueMemberByUserID(ctx context.Context, arg GetItemQueueMemberByUserIDParams) (ItemQueueMember, error)
	GetItemQueueMemberPosition(ctx context.Context, arg GetItemQueueMemberPositionParams) (int32, error)
	LockItemQueue(ctx context.Context, hashtext string) error
	ShiftItemQueueMembersPositions(ctx context.Context, arg ShiftItemQueueMembersPositionsParams) error
	UpdateItemQueue(ctx context.Context, arg UpdateItemQueueParams) error
	UpdateItemQueueMember(ctx context.Context, arg UpdateItemQueueMemberParams) error
}

var _ Querier = (*Queries)(nil)
